import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
    },
    header: {
        alignItems: 'center',
        marginBottom: 40,
        position: 'relative',
    },
    monthText: {
        color: '#4A6FA5',
        fontSize: 14,
        fontWeight: '400',
        marginBottom: 12,
    },
    totalSaved: {
        color: '#162447',
        fontSize: 56,
        fontWeight: '300',
        letterSpacing: -1.5,
    },
    card: {
        backgroundColor: '#F8F9FB',
        borderRadius: 12,
        padding: 24,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#D8DEE9',
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '500',
        marginBottom: 20,
        color: '#162447',
        letterSpacing: -0.3,
    },
    cardRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    cardLabel: {
        color: '#8894A6',
        fontSize: 12,
        fontWeight: '400',
        marginBottom: 6,
    },
    cardValue: {
        color: '#162447',
        fontSize: 20,
        fontWeight: '400',
    },
    progressBarBg: {
        height: 6,
        borderRadius: 3,
        backgroundColor: '#D8DEE9',
        overflow: 'hidden',
        marginTop: 8,
    },
    progressBarFg: {
        height: '100%',
        borderRadius: 3,
        backgroundColor: '#4A6FA5',
    },
    breakdownItem: {
        marginBottom: 24,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#D8DEE9',
    },
    breakdownLabel: {
        marginLeft: 12,
        fontWeight: '400',
        fontSize: 15,
        color: '#162447',
    },
    roundupText: {
        fontSize: 13,
        color: '#8894A6',
        marginBottom: 8,
        marginTop: 8,
    },
    dropdown: {
        position: 'absolute',
        top: 30,
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingVertical: 4,
        paddingHorizontal: 0,
        width: 140,
        zIndex: 10,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#D8DEE9',
    },
    dropdownItem: {
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    dropdownItemText: {
        fontSize: 14,
        fontWeight: '400',
        color: '#162447',
    },
    investmentButton: {
        backgroundColor: '#4A6FA5',
        borderRadius: 12,
        padding: 20,
        marginBottom: 24,
    },
    investmentButtonContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    investmentButtonLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    investmentButtonText: {
        marginLeft: 16,
    },
    investmentButtonTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    investmentButtonSubtitle: {
        fontSize: 13,
        fontWeight: '400',
        color: '#D8DEE9',
    },
});